# -*- coding:utf-8 -*-

__author__ = "Philgyu, Seong"
__email__ = "phil@treasureisle.co"

KEY_SECRET_KEY = "SECRET_KEY"

KEY_SQLALCHEMY_DATABASE_URI = "SQLALCHEMY_DATABASE_URI"

KEY_AWS_ACCESS_KEY_ID = "AWS_ACCESS_KEY_ID"

KEY_AWS_ACCESS_SECRET = "AWS_ACCESS_SECRET"

KEY_S3_BUCKET = "S3_BUCKET"

KEY_WEB_URL = "WEB_URL"

KEY_CDN_URL = "CDN_URL"

KEY_LOCAL_URL = "LOCAL_URL"

KEY_API_URL = "API_URL"

KEY_BROKER_URL = "BROKER_URL"

KEY_CELERY_RESULT_BACKEND = "CELERY_RESULT_BACKEND"

KEY_WWW_URL = "WWW_URL"
